# -*- coding: utf-8 -*-
"""Amazon Sales Performance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NNkyQtb9m3JEFuEHqEcqMcqTnANQdYF
"""

#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Upload the dataset in Google Colab
from google.colab import files

uploaded = files.upload()

#Load the dataset
df = pd.read_csv("amazon_sales_dataset.csv")

df.head()

#Understand the dataset
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

#View basic statistics
df.describe()

#Check missing values
print(df.isnull().sum())

#Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())
#remove duplicates

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

#Convert order date to datetime
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

df.info()

#Create date features
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["month_name"] = df["order_date"].dt.month_name()
df["year_month"] = df["order_date"].dt.to_period("M").astype(str)
df["day_name"] = df["order_date"].dt.day_name()

df.head()

#Check unique values
print("Product Categories:")
print(df["product_category"].unique())

print("\nCustomer Regions:")
print(df["customer_region"].unique())

print("\nPayment Methods:")
print(df["payment_method"].unique())

#Calculate important KPIs
total_revenue = df["total_revenue"].sum()
total_orders = df["order_id"].nunique()
total_quantity = df["quantity_sold"].sum()
average_order_value = total_revenue / total_orders
average_rating = df["rating"].mean()

print("Total Revenue:", round(total_revenue, 2))
print("Total Orders:", total_orders)
print("Total Quantity Sold:", total_quantity)
print("Average Order Value:", round(average_order_value, 2))
print("Average Rating:", round(average_rating, 2))

#Monthly sales trend
monthly_sales = (
    df.groupby("year_month")["total_revenue"]
    .sum()
    .reset_index()
)

print(monthly_sales)

plt.figure(figsize=(12, 6))

plt.plot(
    monthly_sales["year_month"],
    monthly_sales["total_revenue"],
    marker="o"
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Revenue by product category
category_sales = (
    df.groupby("product_category")["total_revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print(category_sales)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=category_sales,
    x="total_revenue",
    y="product_category"
)

plt.title("Revenue by Product Category")
plt.xlabel("Total Revenue")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()

#Quantity sold by product category
category_quantity = (
    df.groupby("product_category")["quantity_sold"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print(category_quantity)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=category_quantity,
    x="quantity_sold",
    y="product_category"
)

plt.title("Quantity Sold by Product Category")
plt.xlabel("Quantity Sold")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()

#Revenue by customer region
region_sales = (
    df.groupby("customer_region")["total_revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print(region_sales)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=region_sales,
    x="customer_region",
    y="total_revenue"
)

plt.title("Revenue by Customer Region")
plt.xlabel("Customer Region")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Payment method analysis
payment_analysis = (
    df.groupby("payment_method")
    .agg(
        Total_Orders=("order_id", "nunique"),
        Total_Revenue=("total_revenue", "sum")
    )
    .sort_values("Total_Revenue", ascending=False)
    .reset_index()
)

print(payment_analysis)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=payment_analysis,
    x="payment_method",
    y="Total_Revenue"
)

plt.title("Revenue by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Top 10 products by revenue

top_products = (
    df.groupby("product_id")["total_revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

print(top_products)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=top_products,
    x="total_revenue",
    y="product_id"
)

plt.title("Top 10 Products by Revenue")
plt.xlabel("Total Revenue")
plt.ylabel("Product ID")
plt.tight_layout()
plt.show()

#Discount analysis
print(df[
    [
        "price",
        "discount_percent",
        "discounted_price",
        "quantity_sold",
        "total_revenue"
    ]
].corr())

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="discount_percent",
    y="quantity_sold"
)

plt.title("Discount Percentage vs Quantity Sold")
plt.xlabel("Discount Percentage")
plt.ylabel("Quantity Sold")
plt.tight_layout()
plt.show()

#Average rating by category
category_rating = (
    df.groupby("product_category")["rating"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

print(category_rating)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=category_rating,
    x="rating",
    y="product_category"
)

plt.title("Average Rating by Product Category")
plt.xlabel("Average Rating")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()

#Review count by category
category_reviews = (
    df.groupby("product_category")["review_count"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print(category_reviews)

#Day-of-week sales analysis
day_sales = (
    df.groupby("day_name")["total_revenue"]
    .sum()
    .reset_index()
)

day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

day_sales["day_name"] = pd.Categorical(
    day_sales["day_name"],
    categories=day_order,
    ordered=True
)

day_sales = day_sales.sort_values("day_name")

print(day_sales)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=day_sales,
    x="day_name",
    y="total_revenue"
)

plt.title("Sales by Day of Week")
plt.xlabel("Day")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Correlation heatmap
numeric_columns = [
    "price",
    "discount_percent",
    "discounted_price",
    "quantity_sold",
    "total_revenue",
    "rating",
    "review_count"
]

correlation = df[numeric_columns].corr()

plt.figure(figsize=(10, 7))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

#Generate a KPI summary
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Revenue",
        "Total Orders",
        "Total Quantity Sold",
        "Average Order Value",
        "Average Rating"
    ],
    "Value": [
        round(total_revenue, 2),
        total_orders,
        total_quantity,
        round(average_order_value, 2),
        round(average_rating, 2)
    ]
})

kpi_summary

#Save the cleaned dataset
df.to_csv("cleaned_amazon_sales.csv", index=False)

print("Cleaned dataset saved successfully.")

from google.colab import files

files.download("cleaned_amazon_sales.csv")